<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-UserTransaction.ServiceB-03181b40-c8d0-47d5-933e-660b3084482b</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\UserTransaction.Shared\UserTransaction.Shared.csproj" />
    </ItemGroup>
</Project>
